#!/bin/bash
set -e

# Read the first branch being pushed. 
# Ploy.sh Currently only supports building one branch at a time
# (Multiple parallel deployment branches would probably be a huge footgun to support)
read oldrev newrev ref

# Extract the branch name
branch=$(echo $ref | cut -d/ -f3)
echo "Checking out branch $branch"

# Checkout the code
mkdir -p worktree
GIT_WORK_TREE=$(pwd)/worktree git checkout -f $branch
cd $(pwd)/worktree

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m' # No Color

# Run the CI/CD steps
if [ -f ploy/build ]; then
    echo "Building..."
    chmod +x ploy/build
    if ./ploy/build ; then
        echo -e "${GREEN}Build complete.${RESET}"
    else
        echo -e "${RED}Build failed.${RESET}"
        exit 1
    fi
fi

if [ -f ploy/test ]; then
    echo "Testing..."
    chmod +x ploy/test
    if ./ploy/test ; then
        echo -e "${GREEN}Test complete.${RESET}"
    else
        echo -e "${RED}Test failed.${RESET}"
        exit 1
    fi
fi

if [ -f ploy/deploy ]; then
    echo "Deploying..."
    chmod +x ploy/deploy
    if ./ploy/deploy ; then
        echo -e "${GREEN}Deploy complete.${RESET}"
    else
        echo -e "${GREEN}Deploy failed.${RESET}"
        exit 1
    fi
fi

echo "Done."
